<?php
/**
 * AcsDecoupleIndicator
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sberbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API платёжного шлюза Сбербанка
 *
 * Настоящий документ описывает программные интерфейсы платёжного шлюза Сбербанка, который позволяет проводить платежи в интернет-эквайринге.
 *
 * The version of the OpenAPI document: 1.0.7
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sberbank\Model;
use \Sberbank\ObjectSerializer;

/**
 * AcsDecoupleIndicator Class Doc Comment
 *
 * @category Class
 * @description Признак обработки операции оплаты по сценарию отложенной аутентификации. Допустимые значения:   * &#x60;Y&#x60; &#x3D; используется отложенная аутентификация
 * @package  Sberbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AcsDecoupleIndicator
{
    /**
     * Possible values of this enum
     */
    public const Y = 'Y';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::Y
        ];
    }
}


