<?php
/**
 * PaymentDirectRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sberbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API платёжного шлюза Сбербанка
 *
 * Настоящий документ описывает программные интерфейсы платёжного шлюза Сбербанка, который позволяет проводить платежи в интернет-эквайринге.
 *
 * The version of the OpenAPI document: 1.0.7
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sberbank\Model;

use \ArrayAccess;
use \Sberbank\ObjectSerializer;

/**
 * PaymentDirectRequest Class Doc Comment
 *
 * @category Class
 * @package  Sberbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentDirectRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'paymentDirectRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'user_name' => 'string',
        'password' => 'string',
        'order_number' => 'string',
        'amount' => 'int',
        'currency_code' => 'string',
        'description' => 'string',
        'language' => 'string',
        'pre_auth' => 'bool',
        'additional_parameters' => '\Sberbank\Model\PaymentDirectRequestAdditionalParameters',
        'client_id' => 'string',
        'payment_token' => 'string',
        'merchant' => 'string',
        'features' => 'string',
        'order_bundle' => '\Sberbank\Model\OrderBundle',
        'phone' => 'string',
        'email' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'user_name' => null,
        'password' => null,
        'order_number' => null,
        'amount' => null,
        'currency_code' => null,
        'description' => null,
        'language' => null,
        'pre_auth' => null,
        'additional_parameters' => null,
        'client_id' => null,
        'payment_token' => null,
        'merchant' => null,
        'features' => null,
        'order_bundle' => null,
        'phone' => null,
        'email' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'user_name' => false,
        'password' => false,
        'order_number' => false,
        'amount' => false,
        'currency_code' => false,
        'description' => false,
        'language' => false,
        'pre_auth' => false,
        'additional_parameters' => false,
        'client_id' => false,
        'payment_token' => false,
        'merchant' => false,
        'features' => false,
        'order_bundle' => false,
        'phone' => false,
        'email' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'user_name' => 'userName',
        'password' => 'password',
        'order_number' => 'orderNumber',
        'amount' => 'amount',
        'currency_code' => 'currencyCode',
        'description' => 'description',
        'language' => 'language',
        'pre_auth' => 'preAuth',
        'additional_parameters' => 'additionalParameters',
        'client_id' => 'clientId',
        'payment_token' => 'paymentToken',
        'merchant' => 'merchant',
        'features' => 'features',
        'order_bundle' => 'orderBundle',
        'phone' => 'phone',
        'email' => 'email'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'user_name' => 'setUserName',
        'password' => 'setPassword',
        'order_number' => 'setOrderNumber',
        'amount' => 'setAmount',
        'currency_code' => 'setCurrencyCode',
        'description' => 'setDescription',
        'language' => 'setLanguage',
        'pre_auth' => 'setPreAuth',
        'additional_parameters' => 'setAdditionalParameters',
        'client_id' => 'setClientId',
        'payment_token' => 'setPaymentToken',
        'merchant' => 'setMerchant',
        'features' => 'setFeatures',
        'order_bundle' => 'setOrderBundle',
        'phone' => 'setPhone',
        'email' => 'setEmail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'user_name' => 'getUserName',
        'password' => 'getPassword',
        'order_number' => 'getOrderNumber',
        'amount' => 'getAmount',
        'currency_code' => 'getCurrencyCode',
        'description' => 'getDescription',
        'language' => 'getLanguage',
        'pre_auth' => 'getPreAuth',
        'additional_parameters' => 'getAdditionalParameters',
        'client_id' => 'getClientId',
        'payment_token' => 'getPaymentToken',
        'merchant' => 'getMerchant',
        'features' => 'getFeatures',
        'order_bundle' => 'getOrderBundle',
        'phone' => 'getPhone',
        'email' => 'getEmail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('user_name', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('order_number', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('currency_code', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('pre_auth', $data ?? [], null);
        $this->setIfExists('additional_parameters', $data ?? [], null);
        $this->setIfExists('client_id', $data ?? [], null);
        $this->setIfExists('payment_token', $data ?? [], null);
        $this->setIfExists('merchant', $data ?? [], null);
        $this->setIfExists('features', $data ?? [], null);
        $this->setIfExists('order_bundle', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['user_name'] === null) {
            $invalidProperties[] = "'user_name' can't be null";
        }
        if ((mb_strlen($this->container['user_name']) > 30)) {
            $invalidProperties[] = "invalid value for 'user_name', the character length must be smaller than or equal to 30.";
        }

        if ((mb_strlen($this->container['user_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'user_name', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[A-Za-z0-9-_ ]+$/", $this->container['user_name'])) {
            $invalidProperties[] = "invalid value for 'user_name', must be conform to the pattern /^[A-Za-z0-9-_ ]+$/.";
        }

        if ($this->container['password'] === null) {
            $invalidProperties[] = "'password' can't be null";
        }
        if ((mb_strlen($this->container['password']) > 30)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be smaller than or equal to 30.";
        }

        if ((mb_strlen($this->container['password']) < 1)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[ -~]+$/", $this->container['password'])) {
            $invalidProperties[] = "invalid value for 'password', must be conform to the pattern /^[ -~]+$/.";
        }

        if ($this->container['order_number'] === null) {
            $invalidProperties[] = "'order_number' can't be null";
        }
        if ((mb_strlen($this->container['order_number']) > 36)) {
            $invalidProperties[] = "invalid value for 'order_number', the character length must be smaller than or equal to 36.";
        }

        if ((mb_strlen($this->container['order_number']) < 1)) {
            $invalidProperties[] = "invalid value for 'order_number', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if (($this->container['amount'] > 999999999999)) {
            $invalidProperties[] = "invalid value for 'amount', must be smaller than or equal to 999999999999.";
        }

        if (($this->container['amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['currency_code']) && (mb_strlen($this->container['currency_code']) > 3)) {
            $invalidProperties[] = "invalid value for 'currency_code', the character length must be smaller than or equal to 3.";
        }

        if (!is_null($this->container['currency_code']) && (mb_strlen($this->container['currency_code']) < 3)) {
            $invalidProperties[] = "invalid value for 'currency_code', the character length must be bigger than or equal to 3.";
        }

        if (!is_null($this->container['currency_code']) && !preg_match("/^\\d{3}$/", $this->container['currency_code'])) {
            $invalidProperties[] = "invalid value for 'currency_code', must be conform to the pattern /^\\d{3}$/.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 512)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) < 1)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['description']) && !preg_match("/^[ -~А-Яа-яЁё№]*$/", $this->container['description'])) {
            $invalidProperties[] = "invalid value for 'description', must be conform to the pattern /^[ -~А-Яа-яЁё№]*$/.";
        }

        if (!is_null($this->container['language']) && (mb_strlen($this->container['language']) > 2)) {
            $invalidProperties[] = "invalid value for 'language', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['language']) && (mb_strlen($this->container['language']) < 2)) {
            $invalidProperties[] = "invalid value for 'language', the character length must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['language']) && !preg_match("/^[a-z]+$/", $this->container['language'])) {
            $invalidProperties[] = "invalid value for 'language', must be conform to the pattern /^[a-z]+$/.";
        }

        if (!is_null($this->container['client_id']) && (mb_strlen($this->container['client_id']) > 255)) {
            $invalidProperties[] = "invalid value for 'client_id', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['client_id']) && (mb_strlen($this->container['client_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'client_id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['client_id']) && !preg_match("/^[ -~]+$/", $this->container['client_id'])) {
            $invalidProperties[] = "invalid value for 'client_id', must be conform to the pattern /^[ -~]+$/.";
        }

        if ($this->container['payment_token'] === null) {
            $invalidProperties[] = "'payment_token' can't be null";
        }
        if ((mb_strlen($this->container['payment_token']) > 8192)) {
            $invalidProperties[] = "invalid value for 'payment_token', the character length must be smaller than or equal to 8192.";
        }

        if ((mb_strlen($this->container['payment_token']) < 1)) {
            $invalidProperties[] = "invalid value for 'payment_token', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[ -~]*$/", $this->container['payment_token'])) {
            $invalidProperties[] = "invalid value for 'payment_token', must be conform to the pattern /^[ -~]*$/.";
        }

        if (!is_null($this->container['merchant']) && (mb_strlen($this->container['merchant']) > 30)) {
            $invalidProperties[] = "invalid value for 'merchant', the character length must be smaller than or equal to 30.";
        }

        if (!is_null($this->container['merchant']) && (mb_strlen($this->container['merchant']) < 1)) {
            $invalidProperties[] = "invalid value for 'merchant', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['merchant']) && !preg_match("/^[A-Za-z0-9-_ ]+$/", $this->container['merchant'])) {
            $invalidProperties[] = "invalid value for 'merchant', must be conform to the pattern /^[A-Za-z0-9-_ ]+$/.";
        }

        if (!is_null($this->container['features']) && (mb_strlen($this->container['features']) > 255)) {
            $invalidProperties[] = "invalid value for 'features', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['features']) && (mb_strlen($this->container['features']) < 1)) {
            $invalidProperties[] = "invalid value for 'features', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['features']) && !preg_match("/^[ -~]*$/", $this->container['features'])) {
            $invalidProperties[] = "invalid value for 'features', must be conform to the pattern /^[ -~]*$/.";
        }

        if (!is_null($this->container['phone']) && (mb_strlen($this->container['phone']) > 16)) {
            $invalidProperties[] = "invalid value for 'phone', the character length must be smaller than or equal to 16.";
        }

        if (!is_null($this->container['phone']) && (mb_strlen($this->container['phone']) < 1)) {
            $invalidProperties[] = "invalid value for 'phone', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['phone']) && !preg_match("/^(\\+?)\\d{7,15}$/", $this->container['phone'])) {
            $invalidProperties[] = "invalid value for 'phone', must be conform to the pattern /^(\\+?)\\d{7,15}$/.";
        }

        if (!is_null($this->container['email']) && (mb_strlen($this->container['email']) > 128)) {
            $invalidProperties[] = "invalid value for 'email', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['email']) && (mb_strlen($this->container['email']) < 3)) {
            $invalidProperties[] = "invalid value for 'email', the character length must be bigger than or equal to 3.";
        }

        if (!is_null($this->container['email']) && !preg_match("/^[ -~]+$/", $this->container['email'])) {
            $invalidProperties[] = "invalid value for 'email', must be conform to the pattern /^[ -~]+$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets user_name
     *
     * @return string
     */
    public function getUserName()
    {
        return $this->container['user_name'];
    }

    /**
     * Sets user_name
     *
     * @param string $user_name Логин Клиента, полученный при подключении к ПШ
     *
     * @return self
     */
    public function setUserName($user_name)
    {
        if (is_null($user_name)) {
            throw new \InvalidArgumentException('non-nullable user_name cannot be null');
        }
        if ((mb_strlen($user_name) > 30)) {
            throw new \InvalidArgumentException('invalid length for $user_name when calling PaymentDirectRequest., must be smaller than or equal to 30.');
        }
        if ((mb_strlen($user_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $user_name when calling PaymentDirectRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[A-Za-z0-9-_ ]+$/", ObjectSerializer::toString($user_name)))) {
            throw new \InvalidArgumentException("invalid value for \$user_name when calling PaymentDirectRequest., must conform to the pattern /^[A-Za-z0-9-_ ]+$/.");
        }

        $this->container['user_name'] = $user_name;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string $password Пароль Клиента, полученный при подключении к ПШ
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        if ((mb_strlen($password) > 30)) {
            throw new \InvalidArgumentException('invalid length for $password when calling PaymentDirectRequest., must be smaller than or equal to 30.');
        }
        if ((mb_strlen($password) < 1)) {
            throw new \InvalidArgumentException('invalid length for $password when calling PaymentDirectRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[ -~]+$/", ObjectSerializer::toString($password)))) {
            throw new \InvalidArgumentException("invalid value for \$password when calling PaymentDirectRequest., must conform to the pattern /^[ -~]+$/.");
        }

        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets order_number
     *
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->container['order_number'];
    }

    /**
     * Sets order_number
     *
     * @param string $order_number Уникальный номер (идентификатор) заказа в системе Клиента. Обязателен, если в запросе отсутствует orderId.
     *
     * @return self
     */
    public function setOrderNumber($order_number)
    {
        if (is_null($order_number)) {
            throw new \InvalidArgumentException('non-nullable order_number cannot be null');
        }
        if ((mb_strlen($order_number) > 36)) {
            throw new \InvalidArgumentException('invalid length for $order_number when calling PaymentDirectRequest., must be smaller than or equal to 36.');
        }
        if ((mb_strlen($order_number) < 1)) {
            throw new \InvalidArgumentException('invalid length for $order_number when calling PaymentDirectRequest., must be bigger than or equal to 1.');
        }

        $this->container['order_number'] = $order_number;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount Сумма операции в минимальных единицах валюты
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }

        if (($amount > 999999999999)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling PaymentDirectRequest., must be smaller than or equal to 999999999999.');
        }
        if (($amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling PaymentDirectRequest., must be bigger than or equal to 0.');
        }

        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string|null $currency_code Цифровой код валюты операции ISO-4217
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {
        if (is_null($currency_code)) {
            throw new \InvalidArgumentException('non-nullable currency_code cannot be null');
        }
        if ((mb_strlen($currency_code) > 3)) {
            throw new \InvalidArgumentException('invalid length for $currency_code when calling PaymentDirectRequest., must be smaller than or equal to 3.');
        }
        if ((mb_strlen($currency_code) < 3)) {
            throw new \InvalidArgumentException('invalid length for $currency_code when calling PaymentDirectRequest., must be bigger than or equal to 3.');
        }
        if ((!preg_match("/^\\d{3}$/", ObjectSerializer::toString($currency_code)))) {
            throw new \InvalidArgumentException("invalid value for \$currency_code when calling PaymentDirectRequest., must conform to the pattern /^\\d{3}$/.");
        }

        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Описание заказа в свободной форме на стороне Клиента. Рекомендуемая длина до 99 символов
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 512)) {
            throw new \InvalidArgumentException('invalid length for $description when calling PaymentDirectRequest., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($description) < 1)) {
            throw new \InvalidArgumentException('invalid length for $description when calling PaymentDirectRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[ -~А-Яа-яЁё№]*$/", ObjectSerializer::toString($description)))) {
            throw new \InvalidArgumentException("invalid value for \$description when calling PaymentDirectRequest., must conform to the pattern /^[ -~А-Яа-яЁё№]*$/.");
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language Язык в кодировке ISO 639-1 (ru, en). Если не указан, будет использовано значение по умолчанию, указанное в настройках Клиента
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        if ((mb_strlen($language) > 2)) {
            throw new \InvalidArgumentException('invalid length for $language when calling PaymentDirectRequest., must be smaller than or equal to 2.');
        }
        if ((mb_strlen($language) < 2)) {
            throw new \InvalidArgumentException('invalid length for $language when calling PaymentDirectRequest., must be bigger than or equal to 2.');
        }
        if ((!preg_match("/^[a-z]+$/", ObjectSerializer::toString($language)))) {
            throw new \InvalidArgumentException("invalid value for \$language when calling PaymentDirectRequest., must conform to the pattern /^[a-z]+$/.");
        }

        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets pre_auth
     *
     * @return bool|null
     */
    public function getPreAuth()
    {
        return $this->container['pre_auth'];
    }

    /**
     * Sets pre_auth
     *
     * @param bool|null $pre_auth Признак предварительной авторизации. Возможны следующие значения:   * `true` = истина, платёж обрабатывается по двухстадийному сценарию;   * `false` = ложь (по умолчанию), платёж обрабатывается по одностадийному сценарию.
     *
     * @return self
     */
    public function setPreAuth($pre_auth)
    {
        if (is_null($pre_auth)) {
            throw new \InvalidArgumentException('non-nullable pre_auth cannot be null');
        }
        $this->container['pre_auth'] = $pre_auth;

        return $this;
    }

    /**
     * Gets additional_parameters
     *
     * @return \Sberbank\Model\PaymentDirectRequestAdditionalParameters|null
     */
    public function getAdditionalParameters()
    {
        return $this->container['additional_parameters'];
    }

    /**
     * Sets additional_parameters
     *
     * @param \Sberbank\Model\PaymentDirectRequestAdditionalParameters|null $additional_parameters additional_parameters
     *
     * @return self
     */
    public function setAdditionalParameters($additional_parameters)
    {
        if (is_null($additional_parameters)) {
            throw new \InvalidArgumentException('non-nullable additional_parameters cannot be null');
        }
        $this->container['additional_parameters'] = $additional_parameters;

        return $this;
    }

    /**
     * Gets client_id
     *
     * @return string|null
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string|null $client_id Номер (идентификатор) Плательщика в системе Клиента. Используется для реализации функционала Связок
     *
     * @return self
     */
    public function setClientId($client_id)
    {
        if (is_null($client_id)) {
            throw new \InvalidArgumentException('non-nullable client_id cannot be null');
        }
        if ((mb_strlen($client_id) > 255)) {
            throw new \InvalidArgumentException('invalid length for $client_id when calling PaymentDirectRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($client_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $client_id when calling PaymentDirectRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[ -~]+$/", ObjectSerializer::toString($client_id)))) {
            throw new \InvalidArgumentException("invalid value for \$client_id when calling PaymentDirectRequest., must conform to the pattern /^[ -~]+$/.");
        }

        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets payment_token
     *
     * @return string
     */
    public function getPaymentToken()
    {
        return $this->container['payment_token'];
    }

    /**
     * Sets payment_token
     *
     * @param string $payment_token Закодированный в base64url JSON-объект с платёжными данными полученными и расшифрованными на стороне Клиента из JWT Payload (Claim) от MirPay. Состав JSON-объекта:   Объект  |Тип     |Обязательно|Описание   --------|--------|-----------|-------------------------------------   tan     |string  |да         |Номер Токена (TAN)   cav     |string  |да/нет     |Authentication Value (NSPK-InApp криптограмма). Может отсутствовать для операций по сохраненным реквизитам   tey     |integer |да         |Последние две цифры года срока окончания действия токена. Возможные значения: 18-99   tem     |integer |да         |Порядковый номер месяца в году срока окончания действия токена. Возможные значения: 1-12   transId |string  |да/нет     |Уникальный идентификатор In-App операции в формате UUID. Может отсутствовать для операций по сохраненным реквизитам   mId     |string  |да/нет     |Идентификатор ТСП (Merchant ID).Может отсутствовать для операций по сохраненным реквизитам   mx5c    |string  |да/нет     |Cертификат X.509 в Base64 открытого ключа ТСП. Может отсутствовать для операций по сохраненным реквизитам   orderId |string  |да/нет     |Уникальный идентификатор заказа/транзакции на стороне ТСП. Может отсутствовать для операций по сохраненным реквизитам   sum     |integer |да/нет     |Сумма платежа в минимальных единицах валюты. Должна совпадать с суммой заказа. Может отсутствовать для операций по сохраненным реквизитам   cur     |integer |да/нет     |Цифровой код валюты по ISO 4217. Может отсутствовать для операций по сохраненным реквизитам   media   |string  |да/нет     |Тип источника, через который инициирована In-App операция. `ISDK` = In-Application SDK, `DL` = Deep link, `UL` = Universal link, `TR` = In-Application Mir HCE SDK
     *
     * @return self
     */
    public function setPaymentToken($payment_token)
    {
        if (is_null($payment_token)) {
            throw new \InvalidArgumentException('non-nullable payment_token cannot be null');
        }
        if ((mb_strlen($payment_token) > 8192)) {
            throw new \InvalidArgumentException('invalid length for $payment_token when calling PaymentDirectRequest., must be smaller than or equal to 8192.');
        }
        if ((mb_strlen($payment_token) < 1)) {
            throw new \InvalidArgumentException('invalid length for $payment_token when calling PaymentDirectRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[ -~]*$/", ObjectSerializer::toString($payment_token)))) {
            throw new \InvalidArgumentException("invalid value for \$payment_token when calling PaymentDirectRequest., must conform to the pattern /^[ -~]*$/.");
        }

        $this->container['payment_token'] = $payment_token;

        return $this;
    }

    /**
     * Gets merchant
     *
     * @return string|null
     */
    public function getMerchant()
    {
        return $this->container['merchant'];
    }

    /**
     * Sets merchant
     *
     * @param string|null $merchant Логин дочернего Клиента (если используется)
     *
     * @return self
     */
    public function setMerchant($merchant)
    {
        if (is_null($merchant)) {
            throw new \InvalidArgumentException('non-nullable merchant cannot be null');
        }
        if ((mb_strlen($merchant) > 30)) {
            throw new \InvalidArgumentException('invalid length for $merchant when calling PaymentDirectRequest., must be smaller than or equal to 30.');
        }
        if ((mb_strlen($merchant) < 1)) {
            throw new \InvalidArgumentException('invalid length for $merchant when calling PaymentDirectRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[A-Za-z0-9-_ ]+$/", ObjectSerializer::toString($merchant)))) {
            throw new \InvalidArgumentException("invalid value for \$merchant when calling PaymentDirectRequest., must conform to the pattern /^[A-Za-z0-9-_ ]+$/.");
        }

        $this->container['merchant'] = $merchant;

        return $this;
    }

    /**
     * Gets features
     *
     * @return string|null
     */
    public function getFeatures()
    {
        return $this->container['features'];
    }

    /**
     * Sets features
     *
     * @param string|null $features Дополнительные параметры управления сценариями при использовании платёжных реквизитов:   * `VERIFY` = Происходит верификация Плательщика без списания средств с его счёта, поэтому в запросе можно передавать нулевую сумму. Даже если сумма платежа будет передана в запросе, она не будет списана со счёта покупателя. После успешной верификации заказ сразу переводится в статус REVERSED (отменён);
     *
     * @return self
     */
    public function setFeatures($features)
    {
        if (is_null($features)) {
            throw new \InvalidArgumentException('non-nullable features cannot be null');
        }
        if ((mb_strlen($features) > 255)) {
            throw new \InvalidArgumentException('invalid length for $features when calling PaymentDirectRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($features) < 1)) {
            throw new \InvalidArgumentException('invalid length for $features when calling PaymentDirectRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[ -~]*$/", ObjectSerializer::toString($features)))) {
            throw new \InvalidArgumentException("invalid value for \$features when calling PaymentDirectRequest., must conform to the pattern /^[ -~]*$/.");
        }

        $this->container['features'] = $features;

        return $this;
    }

    /**
     * Gets order_bundle
     *
     * @return \Sberbank\Model\OrderBundle|null
     */
    public function getOrderBundle()
    {
        return $this->container['order_bundle'];
    }

    /**
     * Sets order_bundle
     *
     * @param \Sberbank\Model\OrderBundle|null $order_bundle order_bundle
     *
     * @return self
     */
    public function setOrderBundle($order_bundle)
    {
        if (is_null($order_bundle)) {
            throw new \InvalidArgumentException('non-nullable order_bundle cannot be null');
        }
        $this->container['order_bundle'] = $order_bundle;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Номер телефона Плательщика. Если в телефон включён код страны, номер должен начинаться со знака плюс («+»). Если телефон передаётся без знака плюс («+»), то код страны указывать не следует. В случае использования фискализации обязателен для передачи в формате +79998887700, при отсутствии номера телефона обязателен email.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        if ((mb_strlen($phone) > 16)) {
            throw new \InvalidArgumentException('invalid length for $phone when calling PaymentDirectRequest., must be smaller than or equal to 16.');
        }
        if ((mb_strlen($phone) < 1)) {
            throw new \InvalidArgumentException('invalid length for $phone when calling PaymentDirectRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^(\\+?)\\d{7,15}$/", ObjectSerializer::toString($phone)))) {
            throw new \InvalidArgumentException("invalid value for \$phone when calling PaymentDirectRequest., must conform to the pattern /^(\\+?)\\d{7,15}$/.");
        }

        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Адрес электронной почты Плательщика. В случае использования фискализации обязателен, при отсутствии phone.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        if ((mb_strlen($email) > 128)) {
            throw new \InvalidArgumentException('invalid length for $email when calling PaymentDirectRequest., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($email) < 3)) {
            throw new \InvalidArgumentException('invalid length for $email when calling PaymentDirectRequest., must be bigger than or equal to 3.');
        }
        if ((!preg_match("/^[ -~]+$/", ObjectSerializer::toString($email)))) {
            throw new \InvalidArgumentException("invalid value for \$email when calling PaymentDirectRequest., must conform to the pattern /^[ -~]+$/.");
        }

        $this->container['email'] = $email;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


