<?php
/**
 * RecurrentPaymentResponseOrderStatusCardAuthInfo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sberbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API платёжного шлюза Сбербанка
 *
 * Настоящий документ описывает программные интерфейсы платёжного шлюза Сбербанка, который позволяет проводить платежи в интернет-эквайринге.
 *
 * The version of the OpenAPI document: 1.0.7
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sberbank\Model;

use \ArrayAccess;
use \Sberbank\ObjectSerializer;

/**
 * RecurrentPaymentResponseOrderStatusCardAuthInfo Class Doc Comment
 *
 * @category Class
 * @description Блок информации о Токене Плательщика
 * @package  Sberbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RecurrentPaymentResponseOrderStatusCardAuthInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'recurrentPaymentResponse_orderStatus_cardAuthInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'masked_pan' => 'string',
        'expiration' => 'string',
        'card_holder_name' => 'string',
        'payment_system' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'masked_pan' => null,
        'expiration' => null,
        'card_holder_name' => null,
        'payment_system' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'masked_pan' => false,
        'expiration' => false,
        'card_holder_name' => false,
        'payment_system' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'masked_pan' => 'maskedPan',
        'expiration' => 'expiration',
        'card_holder_name' => 'cardHolderName',
        'payment_system' => 'paymentSystem'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'masked_pan' => 'setMaskedPan',
        'expiration' => 'setExpiration',
        'card_holder_name' => 'setCardHolderName',
        'payment_system' => 'setPaymentSystem'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'masked_pan' => 'getMaskedPan',
        'expiration' => 'getExpiration',
        'card_holder_name' => 'getCardHolderName',
        'payment_system' => 'getPaymentSystem'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('masked_pan', $data ?? [], null);
        $this->setIfExists('expiration', $data ?? [], null);
        $this->setIfExists('card_holder_name', $data ?? [], null);
        $this->setIfExists('payment_system', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['masked_pan']) && (mb_strlen($this->container['masked_pan']) > 20)) {
            $invalidProperties[] = "invalid value for 'masked_pan', the character length must be smaller than or equal to 20.";
        }

        if (!is_null($this->container['masked_pan']) && (mb_strlen($this->container['masked_pan']) < 1)) {
            $invalidProperties[] = "invalid value for 'masked_pan', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['masked_pan']) && !preg_match("/^[0-9*]+$/", $this->container['masked_pan'])) {
            $invalidProperties[] = "invalid value for 'masked_pan', must be conform to the pattern /^[0-9*]+$/.";
        }

        if (!is_null($this->container['expiration']) && (mb_strlen($this->container['expiration']) > 8)) {
            $invalidProperties[] = "invalid value for 'expiration', the character length must be smaller than or equal to 8.";
        }

        if (!is_null($this->container['expiration']) && (mb_strlen($this->container['expiration']) < 1)) {
            $invalidProperties[] = "invalid value for 'expiration', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['expiration']) && !preg_match("/^\\d+$/", $this->container['expiration'])) {
            $invalidProperties[] = "invalid value for 'expiration', must be conform to the pattern /^\\d+$/.";
        }

        if (!is_null($this->container['card_holder_name']) && (mb_strlen($this->container['card_holder_name']) > 200)) {
            $invalidProperties[] = "invalid value for 'card_holder_name', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['card_holder_name']) && (mb_strlen($this->container['card_holder_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'card_holder_name', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['card_holder_name']) && !preg_match("/^[ -~]+$/", $this->container['card_holder_name'])) {
            $invalidProperties[] = "invalid value for 'card_holder_name', must be conform to the pattern /^[ -~]+$/.";
        }

        if (!is_null($this->container['payment_system']) && (mb_strlen($this->container['payment_system']) > 10)) {
            $invalidProperties[] = "invalid value for 'payment_system', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['payment_system']) && (mb_strlen($this->container['payment_system']) < 1)) {
            $invalidProperties[] = "invalid value for 'payment_system', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['payment_system']) && !preg_match("/^\\w+$/", $this->container['payment_system'])) {
            $invalidProperties[] = "invalid value for 'payment_system', must be conform to the pattern /^\\w+$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets masked_pan
     *
     * @return string|null
     */
    public function getMaskedPan()
    {
        return $this->container['masked_pan'];
    }

    /**
     * Sets masked_pan
     *
     * @param string|null $masked_pan Маскированный номер Карты, Токена или Счёта Плательщика
     *
     * @return self
     */
    public function setMaskedPan($masked_pan)
    {
        if (is_null($masked_pan)) {
            throw new \InvalidArgumentException('non-nullable masked_pan cannot be null');
        }
        if ((mb_strlen($masked_pan) > 20)) {
            throw new \InvalidArgumentException('invalid length for $masked_pan when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must be smaller than or equal to 20.');
        }
        if ((mb_strlen($masked_pan) < 1)) {
            throw new \InvalidArgumentException('invalid length for $masked_pan when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[0-9*]+$/", ObjectSerializer::toString($masked_pan)))) {
            throw new \InvalidArgumentException("invalid value for \$masked_pan when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must conform to the pattern /^[0-9*]+$/.");
        }

        $this->container['masked_pan'] = $masked_pan;

        return $this;
    }

    /**
     * Gets expiration
     *
     * @return string|null
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param string|null $expiration Год и месяц истечения срока действия Карты (YYYYMM)
     *
     * @return self
     */
    public function setExpiration($expiration)
    {
        if (is_null($expiration)) {
            throw new \InvalidArgumentException('non-nullable expiration cannot be null');
        }
        if ((mb_strlen($expiration) > 8)) {
            throw new \InvalidArgumentException('invalid length for $expiration when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must be smaller than or equal to 8.');
        }
        if ((mb_strlen($expiration) < 1)) {
            throw new \InvalidArgumentException('invalid length for $expiration when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\d+$/", ObjectSerializer::toString($expiration)))) {
            throw new \InvalidArgumentException("invalid value for \$expiration when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must conform to the pattern /^\\d+$/.");
        }

        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets card_holder_name
     *
     * @return string|null
     */
    public function getCardHolderName()
    {
        return $this->container['card_holder_name'];
    }

    /**
     * Sets card_holder_name
     *
     * @param string|null $card_holder_name Текст, изображенный на Карте Плательщика в ISO 8859-1. Допустимы Имя, Фамилия, инициалы или любые комбинации специальных символов ASCII, кроме кириллицы
     *
     * @return self
     */
    public function setCardHolderName($card_holder_name)
    {
        if (is_null($card_holder_name)) {
            throw new \InvalidArgumentException('non-nullable card_holder_name cannot be null');
        }
        if ((mb_strlen($card_holder_name) > 200)) {
            throw new \InvalidArgumentException('invalid length for $card_holder_name when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must be smaller than or equal to 200.');
        }
        if ((mb_strlen($card_holder_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $card_holder_name when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[ -~]+$/", ObjectSerializer::toString($card_holder_name)))) {
            throw new \InvalidArgumentException("invalid value for \$card_holder_name when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must conform to the pattern /^[ -~]+$/.");
        }

        $this->container['card_holder_name'] = $card_holder_name;

        return $this;
    }

    /**
     * Gets payment_system
     *
     * @return string|null
     */
    public function getPaymentSystem()
    {
        return $this->container['payment_system'];
    }

    /**
     * Sets payment_system
     *
     * @param string|null $payment_system Наименование платёжной системы. Возможны следующие варианты:   * `VISA`;   * `MASTERCARD`;   * `AMEX`;   * `JCB`;   * `CUP`;   * `MIR`;   * `Undefined`- передается в случае, если оплата выполнялась с использованием Счёта.
     *
     * @return self
     */
    public function setPaymentSystem($payment_system)
    {
        if (is_null($payment_system)) {
            throw new \InvalidArgumentException('non-nullable payment_system cannot be null');
        }
        if ((mb_strlen($payment_system) > 10)) {
            throw new \InvalidArgumentException('invalid length for $payment_system when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must be smaller than or equal to 10.');
        }
        if ((mb_strlen($payment_system) < 1)) {
            throw new \InvalidArgumentException('invalid length for $payment_system when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\w+$/", ObjectSerializer::toString($payment_system)))) {
            throw new \InvalidArgumentException("invalid value for \$payment_system when calling RecurrentPaymentResponseOrderStatusCardAuthInfo., must conform to the pattern /^\\w+$/.");
        }

        $this->container['payment_system'] = $payment_system;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


