<?php
/**
 * BindingServicesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Sberbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API платёжного шлюза Сбербанка
 *
 * Настоящий документ описывает программные интерфейсы платёжного шлюза Сбербанка, который позволяет проводить платежи в интернет-эквайринге.
 *
 * The version of the OpenAPI document: 1.0.7
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Sberbank\Test\Api;

use \Sberbank\Configuration;
use \Sberbank\ApiException;
use \Sberbank\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BindingServicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sberbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BindingServicesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bindCard
     *
     * Активация связки Плательщика [bindCard].
     *
     */
    public function testBindCard()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBindings
     *
     * Получение связок по идентификатору Плательщика [getBindings].
     *
     */
    public function testGetBindings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBindingsByCardOrId
     *
     * Получение связок по номеру карты или идентификатору связки Плательщика [getBindingsByCardOrId].
     *
     */
    public function testGetBindingsByCardOrId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentOrderBinding
     *
     * Проведение оплаты по связке [paymentOrderBinding].
     *
     */
    public function testPaymentOrderBinding()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recurrentPayment
     *
     * Проведение периодического платежа [recurrentPayment].
     *
     */
    public function testRecurrentPayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unBindCard
     *
     * Деактивация связки Плательщика [unbindCard].
     *
     */
    public function testUnBindCard()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
